---
  name: 'Run Pylint'
  on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - '**'

  jobs:
    build:
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@v4
      - name: Analyzing the code with python pylint
        shell: bash
        working-directory: ./suika
        run: |
          source ./bootstrap.sh
          pylint -d duplicate-code -d fixme ./suika --output=pylint-scan-result
          cat pylint-scan-result